version: "2"
services:
 web: 
    restart: always
    build: .  
    image: nodeReactApp:latest
    volumes:
      - /var/www/app/
      - /var/www/app/node_modules/
      - /var/www/app/src/
      - /var/www/app/public/
    ports:
      - "3000:3000" 
    image: node-react-app
    command: "npm start"